### ISSUE TITLE
好看，会加入评论模块吗

### ISSUE THREAD

**Issue by gwokming** [shixiaohu2206/hexo-theme-utone#1]
什么时候加入评论模块

**Comment by ryanlijianchang** [comment]
同问，什么时候加入评论模块？

**Comment by gwokming** [comment]
> 同问，什么时候加入评论模块？

看样子作者是没回复了，fork一下自己添加把哈哈哈

**Comment by ryanlijianchang** [comment]
> > 同问，什么时候加入评论模块？
> 
> 看样子作者是没回复了，fork一下自己添加把哈哈哈

求加，我对前端不是很熟悉

**Comment by gwokming** [comment]
> > > 同问，什么时候加入评论模块？
> > 
> > 
> > 看样子作者是没回复了，fork一下自己添加把哈哈哈
> 
> 求加，我对前端不是很熟悉

额，，很简单的可以用gitalk，或者其他评论插件，在内容模板加几行代码就ok了，评论模块会自动生成

**Comment by shixiaohu2206** [comment]
不好意思，没注意有人提issues。。。

我有空来添加一下，我一般都用畅言。

**Comment by shixiaohu2206** [comment]
> > > > 同问，什么时候加入评论模块？
> > > 
> > > 
> > > 看样子作者是没回复了，fork一下自己添加把哈哈哈
> > 
> > 
> > 求加，我对前端不是很熟悉
> 
> 额，，很简单的可以用gitalk，或者其他评论插件，在内容模板加几行代码就ok了，评论模块会自动生成

不好意思，没注意有人提issues。。。

我有空来添加一下，我一般都用畅言。

**Comment by shixiaohu2206** [comment]
> 什么时候加入评论模块

hi，已添加了畅言评论，但是这主题以后不会再更新了，我重新写了另外一个主题https://github.com/shixiaohu2206/hexo-theme-huhu

**Comment by shixiaohu2206** [comment]
> 同问，什么时候加入评论模块？

hi，已添加了畅言评论，但是这主题以后不会再更新了，我重新写了另外一个主题https://github.com/shixiaohu2206/hexo-theme-huhu
